Console.Clear();
Console.WriteLine("Seja bem vindo ao Pet Hotel!");
Console.WriteLine("Qual a espécie de seu animal?");
string especie;
especie = Console.ReadLine()!;
Console.WriteLine($"Qual a raça do seu/sua {especie}? ");
Console.WriteLine("Caso não saiba, digite 'indefinida'");
string raça;
raça = Console.ReadLine()!;
Console.WriteLine($"Qual o nome do seu/sua {especie}?");
string nome;
nome = Console.ReadLine()!;
Console.WriteLine($"Qual a idade de seu/sua {especie}");
int idade;
idade = Convert.ToInt32(Console.ReadLine()!);
Console.WriteLine($"Qual a cor da pelugem de seu/sua {especie}?");
string cor;
cor = Console.ReadLine()!;
Console.WriteLine("Fazendo registro, aguarde uns instantes...");
Thread.Sleep(3500);
Console.WriteLine("");
Console.WriteLine("+===============================================================+");
Console.WriteLine("|                   Pet Hotel 'Nem um pio'                      |");
Console.WriteLine("+===============================================================+");
Console.WriteLine($"| Espécie: ............{especie.ToUpper()}| Raça: ............{raça.ToUpper()}    |");
Console.WriteLine("+===============================================================+");
Console.WriteLine($"| Atende pela alcunha de: ...........................{nome.ToUpper()}     |");
Console.WriteLine($"| Idade: {idade} ano(s) | Pelagem/cor: ...............{cor.ToUpper()}          |");
Console.WriteLine("+===============================================================+"); 
Console.WriteLine("");
Console.WriteLine("");
